json.extract! restaurant, 
    :id,
    :name,
    :description,
    :cuisine, :address,
    :city,
    :state,
    :zipcode,
    :phone_number,
    :open_time,
    :close_time,
    :rating,
    :price_range,
    :owner_id