json.extract! review,
    :id,
    :overall_rating,
    :food_rating,
    :service_rating,
    :ambience_rating,
    :value_rating,
    :noise_level,
    :body,
    :created_at,
    :updated_at,
    :author_id,
    :restaurant_id